### ISSUE TITLE
Perperually falling invulnerable mobs

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#10]
# Current behavior
In GN, paladins will sometimes get stuck in an infinite falling animation, essentially bricking the run since the party can no longer progress.

Some skills trigger this, but I don't remember which one off the top of my head.
More info: https://discord.com/channels/544827049752264704/803135119665266718/884927897985491035

**Comment by wellme** [comment]
Also happens in dungeons.
I remember hearing that this was caused by certain skills in particular. I don't remember which one though
![](https://cdn.discordapp.com/attachments/803135119665266718/960000409018179694/unknown.png)
![](https://cdn.discordapp.com/attachments/544827049752264707/959432002807926784/DN_2022-04-01_08-39-10_Fri.jpg)

**Comment by vincentzhang96** [comment]
If we can get even a moderately sized list of skills that would make tracking this down a lot easier, since this doesn't seem to be specific to mobs but rather a skill setting an invalid knockup velocity

**Comment by wellme** [comment]
[Awakened] Double somersault
https://cdn.discordapp.com/attachments/803135119665266718/963944288696287292/out.mp4

**Comment by vincentzhang96** [comment]
Looked into Awakened Double Somersault, hit blocks aren't really doing anything weird (though the velocity seems a little low). May be able to figure out if we correlate with other trigger skills
