### ISSUE TITLE
Skill description issues

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#139]
MK rework:
https://discord.com/channels/544827049752264704/663884349367910413/1024971671532228608
https://discord.com/channels/544827049752264704/663884349367910413/1024972432978751538

**Comment by wellme** [comment]
Guard HoG: https://discord.com/channels/544827049752264704/663884349367910413/1024833997311852605

**Comment by wellme** [comment]
BP draw blood A: heals for 0.5%, idk about the CDR but it's probably wrong https://reference.fatduckdn.com/skills/6960-Enhanced-Draw-Blood-(A)

**Comment by vincentzhang96** [comment]
HoG one fixed
