### ISSUE TITLE
Bad params on cast cassia buffs

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#144]
Action speed is broken, movement speed is probably fine idk
https://reference.fatduckdn.com/skills/10370-[Awakened]-Cast-Cassia

**Comment by vincentzhang96** [comment]
The effects in this skill are conditional on PRE_MOD_ACTOR_ACTION_SPEED being supported; right now this does nothing. Looks like it intends to only be active during Move_* actions and dashing
