### ISSUE TITLE
Shooting Star CM2

### ISSUE THREAD

**Issue by vincentzhang96** [ProjectDuckDN/IssueTracker#156]
https://discord.com/channels/544827049752264704/803135119665266718/1064879492172091423

Where does this occur: PvE

What is wrong: 
1. Class Bug - Shooting Star's Class Mastery II effect 
1a. "Pressing Regular Attack Button after using [Star Burst] will cast [Super Ball Instant]" does not work
1b. "When [Star Burst] hits enemies, the cooldown of [Superball] is reset" also does not work

What is the expected outcome: 
1. Effect 1 and effect 2 above from Shooting Star's Class Mastery II is working as intended
How to replicate the bug: Take Shooting Star's Class Mastery II and try to use Star Burst then Super Ball

**Comment by wellme** [comment]
Reopened because I only fixed the 2nd part (the CD reset)
