### ISSUE TITLE
[Ride] power punch lvl 3 shows mdmg rather than pdmg in tooltip

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#23]
https://reference.fatduckdn.com/skills/4976-[Ride]-Power-Punch?r=3
![](https://cdn.discordapp.com/attachments/663884349367910413/850804925192470548/IMG_20210605_213234.jpg)

**Comment by vincentzhang96** [comment]
Fixed in v773, tooltip and mdmg updated to 45.6k%
