### ISSUE TITLE
Ruina's ducking is used twice when airborne

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#32]
# Current behavior
When using ducking after FKK or kidney blow, the character will actually duck twice.
More info: https://discord.com/channels/544827049752264704/803135119665266718/940033362087776347

# Expected behavior
Should only duck once

# Steps to reproduce
_How to replicate the issue, if applicable_
1. FKK > left click for the second attack
2. Space to use ducking

**Comment by joooorji** [comment]
This might be intended behavior and not a bug at least on ED's end. They created a new action specifically for these two skills called Ducking_Air instead of Ducking.
