### ISSUE TITLE
DPS parser's instant DPS column reports the wrong number

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#34]
# Current behavior
The instant DPS column is reporting the same number as the total DPS column
![image](https://user-images.githubusercontent.com/7041069/159145328-086f95fd-65ec-4122-aab5-e6d6989f13a9.png)

# Expected behavior
It should show the current DPS instead

**Comment by vincentzhang96** [comment]
Fixed in pd-core:test, will fasttrack to public after verification

**Comment by wellme** [comment]
Confirmed, works fine

**Comment by vincentzhang96** [comment]
Cherry-picked to pd-core:public
