### ISSUE TITLE
DPS parser icons are not vertically centered

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#35]
# Current behavior
1 pixel too high ! All 4 of them have this issue
![image](https://user-images.githubusercontent.com/7041069/159145426-d27ccd8a-0fff-469d-8c82-bd6ffdf61cef.png)

**Comment by wellme** [comment]
Technically, they are now half a pixel too low, but it's basically unnoticeable, so I think closing this is fine ![image](https://user-images.githubusercontent.com/7041069/160992748-ac883576-416f-4f36-b572-edea8c40db9b.png)

**Comment by vincentzhang96** [comment]
I can't do any better than that sadly :c
