### ISSUE TITLE
Magma monument does not show up on pd-core's damage spread

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#44]
# Current behavior
It just doesn't
![image](https://user-images.githubusercontent.com/7041069/161178197-3db71b43-2805-4e63-8fa1-f1fa509ebf9e.png)

**Comment by vincentzhang96** [comment]
Check this after today's pd-core build

**Comment by wellme** [comment]
Well, it shows up but...
8.3b vs 6.9b
![image](https://user-images.githubusercontent.com/7041069/163527332-4e9ce22c-e53f-4068-820d-11cc5344a0f6.png)

**Comment by wellme** [comment]
Never mind, I had damage carry over from Pebbles.
