### ISSUE TITLE
Toxic spill has a trailling space character

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#47]
```Toxic Spill ``` > ```Toxic Spill```
![image](https://user-images.githubusercontent.com/7041069/162314652-da56da7d-d556-49c1-8586-b24e93af3610.png)
![image](https://user-images.githubusercontent.com/7041069/162314748-40a0ad1c-200c-480a-8ea0-1c6db242c76a.png)
![image](https://user-images.githubusercontent.com/7041069/162314863-fe9aad7f-04f6-4853-a3de-e17b4267a69b.png)

**Comment by vincentzhang96** [comment]
Fixed, along with several other skills that also have the same issue
