### ISSUE TITLE
Graphical artifacts using volumetric fog removal

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#54]
# Current behavior
I don't know
![](https://cdn.discordapp.com/attachments/561299409476780032/963915128183599174/unknown.png)
https://discord.com/channels/544827049752264704/561299409476780032/963915129068601345

# Expected behavior
Not that

**Comment by vincentzhang96** [comment]
Feature was removed a while ago, forgot to close issue
