### ISSUE TITLE
Some parries do not give an iframe

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#6]
# Current behavior
When parrying an attack, normal parries give an iframe in order to negate the damage / debuff dealt by composite hits.

- [Rangrid] Counter flare
- [Knightess] Parrying step (both awakened and unawakened)
- [Knightess] Splitter (both EX and non-EX)
- [Ava] Fatal stinger
- [GM] [Awakened quackum crash](https://discord.com/channels/544827049752264704/803135119665266718/892529196901990410)

**Comment by vincentzhang96** [comment]
- Added 10 frame iframe to Counter Flare (parry version only)
- Parrying step already has one, but isn't working?
- Not possible
- Not possible

**Comment by wellme** [comment]
Parrying step
https://user-images.githubusercontent.com/7041069/161672309-3269dc90-8c69-4959-913d-68f9f0254de0.mp4

**Comment by wellme** [comment]
Quantum crash now has an iframe: https://news.fatduckdn.com/patch-v782/

**Comment by joooorji** [comment]
Parrying Step is weird. It shows that it has an iframe instantly on casting, then a brief 20f period of no iframe at the same time as the parrying block and then another iframe block after that. I'm gonna try making all of the cast (non-parry action) non-iframe and then the successful parry an iframe and see if that fixes it.
