### ISSUE TITLE
Tumble and dash descriptions need updating

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#60]
# Current behavior
Double tapping is disabled by default. Also for dash you can only do it going forward
![image](https://user-images.githubusercontent.com/7041069/164128390-eed87152-d75b-446d-95ed-9a222d3792a9.png)
![image](https://user-images.githubusercontent.com/7041069/164128405-2a000aa9-8842-4034-bc1f-dbfd74eaf5c2.png)

**Comment by vincentzhang96** [comment]
Updated for next patch
