### ISSUE TITLE
Nest infos need updating

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#68]
4man has infinite revives
![image](https://user-images.githubusercontent.com/7041069/167317029-f79970b2-9ce8-4c39-88e0-34c737c5548a.png)

VC has 5 revives
![image](https://user-images.githubusercontent.com/7041069/167317051-15a82875-acba-4bec-b181-4a1edccecf68.png)

IDN norm has infinite revives
![image](https://user-images.githubusercontent.com/7041069/167317069-cc443037-dbd7-446b-9ef4-d012027fca12.png)

KTN has revives after every boss iirc
![image](https://user-images.githubusercontent.com/7041069/167317092-8ef89530-b84c-4581-9555-67ebbe030270.png)

GDN's formatting is inconsistent with the others: ``Revives: 1 after every gate`` vs ``Party is revived after every boss``
![image](https://user-images.githubusercontent.com/7041069/167317108-445578b6-69ba-4584-b892-8aa96808f112.png)

**Comment by vincentzhang96** [comment]
Fixed all but RDNVC4
