### ISSUE TITLE
Immortality vertical range UP !

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#79]
wacky woohoo JOORJIMAN :zeke: can go up and down just as fast and doesn't jump over a very small buff area to do the funny thing

**Comment by vincentzhang96** [comment]
Omg its hilariously short
![image](https://user-images.githubusercontent.com/6023772/169865409-24571699-da98-4f1b-93ad-449ce5c1adc3.png)

**Comment by vincentzhang96** [comment]
Height is now consistent with class buffs
