### ISSUE TITLE
Imapctor leakages in PVP

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#86]
# Current behavior

[Awakened] Limit runner gives 2 red bubbles on hit

[Awakened passive] Trigger reduces T-operate's cooldown from 60s to 50s (and also removes its mana cost):
https://reference.fatduckdn.com/skills/10115-T-Operate?pvp=1
https://reference.fatduckdn.com/skills/10282-T-Operate?pvp=1

CM3 can be used after doing a regular attack after cancelling the rolling portion of fly-by. It also allows you to use the intense shock follow-up without consuming / requiring a red bubble

https://user-images.githubusercontent.com/7041069/175483782-233d7c81-93b6-49ed-bd0d-55bc7469b891.mp4

# Expected behavior
No

**Comment by wellme** [comment]
Trigger has a PVP description instead of the usual "Not applicable in PVP.":
https://reference.fatduckdn.com/skills/10253-[Awakened-Passive]-Trigger?pvp=1

A few PVP descriptions are empty:
https://reference.fatduckdn.com/skills/10208-Class-Mastery-II?pvp=1
https://reference.fatduckdn.com/skills/10252-[Awakened-Passive]-Illusive-Fist?pvp=1
https://reference.fatduckdn.com/skills/10255-[Awakened-Passive]-Limit-Runner?pvp=1
https://reference.fatduckdn.com/skills/10254-[Awakened-Passive]-Wide-Intent?pvp=1

**Comment by joooorji** [comment]
CM3 should be fixed
