### ISSUE TITLE
Jade spear isn't held properly

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#9]
# Current behavior
![](https://cdn.discordapp.com/attachments/607797802101243925/883796932856807444/unknown.png)
![](https://cdn.discordapp.com/attachments/607797802101243925/883796954990137394/unknown.png)

More info: https://discord.com/channels/544827049752264704/803135119665266718/885061762007855125
https://discord.com/channels/544827049752264704/607797802101243925/883796935918637087

**Comment by vincentzhang96** [comment]
Fixed for v773
![image](https://user-images.githubusercontent.com/6023772/157729224-3a5df75e-7588-45ca-b092-1dc7000749d4.png)
