### ISSUE TITLE
Some debuff durations are below the standard 20s

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#90]
# Current behavior

https://reference.fatduckdn.com/skills/55-[Nightmare]-Execute
https://reference.fatduckdn.com/skills/4551-Lovesick
https://reference.fatduckdn.com/skills/6604-Outbreak-EX
https://reference.fatduckdn.com/skills/7731-Steam-Release
https://reference.fatduckdn.com/skills/7532-Soul-Cutter-Instant

https://reference.fatduckdn.com/skills/805-[Awakened]-Forward-Thrust
https://reference.fatduckdn.com/skills/823-[Awakened]-Cyclone-Slash
https://reference.fatduckdn.com/skills/1511-[Awakened]-Mortar-Strike
https://reference.fatduckdn.com/skills/1354-Rapid-Shot-EX
https://reference.fatduckdn.com/skills/1401-Ring-Shot
https://reference.fatduckdn.com/skills/2304-Inferno-EX
https://reference.fatduckdn.com/skills/2504-Nine-Tail-Laser-EX
https://reference.fatduckdn.com/skills/4910-Atomic-Blade
https://reference.fatduckdn.com/skills/5333-[Awakened]-Hands-of-Vengeance
https://reference.fatduckdn.com/skills/5310-Hands-of-Vengeance-EX-Instant
https://reference.fatduckdn.com/skills/5403-Soul-Shriek
https://reference.fatduckdn.com/skills/5502-Chakram-Flurry-EX
https://reference.fatduckdn.com/skills/5603-Dusk-Hunter-EX

Some ray mech skills that I don't know if they are actually used but I'm gonna list them for completion sake:
https://reference.fatduckdn.com/skills/4922-Ray:-Atomic-Blade
https://reference.fatduckdn.com/skills/4924-[Enhanced]-Atomic-Blade

**Comment by Atthorpe** [comment]
im on it

**Comment by joooorji** [comment]
Have fun updating all the descriptions

**Comment by wellme** [comment]
Atthorpe is now experiencing a shoebill moment !

**Comment by Atthorpe** [comment]
xd

**Comment by Atthorpe** [comment]
only changing pve ones correct?

**Comment by joooorji** [comment]
yes

**Comment by Atthorpe** [comment]
done
