### ISSUE TITLE
Physician's CM3 is unelemental

### ISSUE THREAD

**Issue by wellme** [ProjectDuckDN/IssueTracker#97]
# Current behavior
Force bump's slime detonation is unelemental

https://user-images.githubusercontent.com/7041069/179862284-2ec0e542-ed8b-44a1-8fe6-0afba9be485c.mp4

# Expected behavior
Damage should be elemental

# Steps to reproduce
_How to replicate the issue, if applicable_
1. Use force bump (dark attack, this one is fine)
2. Use poison pop
3. The slime left behind by force bump explodes, dealing unelemental damage

**Comment by joooorji** [comment]
As it stands right now, the Slime left behind will not even deal 200% of Force Bump's dmg. It seems that Poison Pop is telling the Slime to deal 200% of POISON POP's damage instead LMFAO? But since it's non-ele it's pretty weak.

**Comment by joooorji** [comment]
20x base Poison Pop dmg actually/????
